#!/bin/bash
set -eu
# Check directory
cd "$(dirname "$0")"
[ -d .git ] || cd ../..
[ -d .git ]

pre_commit() {
	ruff check .
	black --check .
	mypy .
}

fix_all() {
	black .
	ruff check --fix-only .
}
format() {
	black .
}

# Commands
case "${1:-run}" in
	run|lint)
		pre_commit
		echo "All good to commit"
		;;
	fix)
		fix_all
		;;
	format)
		format
		;;
	install)
		echo "Installing pre-commit"
		cd .git/hooks
		ln -sf ../../pre-commit pre-commit
		;;
	uninstall)
		echo "Uninstalling pre-commit"
		rm -f .git/hooks/pre-commit
		;;
	*)
		echo "Invalid argument: $*"
		echo "Supported options: lint, format, install, uninstall"
esac
