name: Lint and test

on:
  push:
    branches:
      - "**"
    tags-ignore: ["**"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        # use minimum version here from setup.py
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run pre-commit checks
      run: |
        ./pre-commit
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # lowest, common (defaut ubuntu LTS), newest
        python-version: ["3.8", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pytest
    - name: Run mypy
      run: |
        mypy --install-types --non-interactive .
    - name: Run examples
      run: |
        ./example-simple.py
        python example-inv.py -h

