name: Lint

on:
  push:
    branches:
      - "*"
    tags-ignore: ["*"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        # use minimum version here from setup.py
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run pre-commit checks
      run: |
        ./pre-commit
